# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=                           #
        intel-lpmd                  # low power
        intel-media-driver          # video acceleration
        intel-npu-driver            # npu
        intel-ucode                 # microcode
        linux-firmware-intel        # firmware
        openvino                    # ai
        openvino-intel-gpu-plugin   # ai
        openvino-intel-npu-plugin   # ai
        sof-firmware                # audio
        vulkan-intel                # gpu
