# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=                       #
        flatpak                 # apps
        fnott                   # notifications
        foot                    # terminal
        fuzzel                  # menu
        greetd-tuigreet         # greeter
        i3status                # statusbar
        noto-fonts              # fonts
        noto-fonts-cjk          # fonts
        noto-fonts-emoji        # fonts
        noto-fonts-extra        # fonts
        oo7                     # secrets
        pipewire                # audio
        pipewire-alsa           # audio
        pipewire-audio          # audio
        pipewire-jack           # audio
        pipewire-pulse          # audio
        sway                    # compositor
        swaybg                  # wallpaper
        swayidle                # idle daemon
        swaylock                # lock screen
        ttf-jetbrains-mono-nerd # fonts
        uwsm                    # session manager
        wireplumber             # audio
        wl-clipboard            # clipboard
        wob                     # osd
        xdg-desktop-portal-wlr  # screenshare, etc.

RemoveFiles=
        /usr/share/wayland-sessions/sway.desktop    # only uwsm based session should remain

KernelCommandLine=plymouth.use-simpledrm quiet splash

KernelInitrdModules=/drivers/gpu/drm

InitrdProfiles=plymouth
