# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        flatpak
        greetd-tuigreet
        niri
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        noto-fonts-extra
        rio
        vulkan-intel
