# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=                       #
        bluez                   # bluetooth
        bluez-utils             # bluetooth
        brightnessctl           # display
        iwd                     # wlan
        libmbim                 # wwan
        power-profiles-daemon   # power management
        wireless-regdb          # regulatory database
