# SPDX-License-Identifier: LGPL-2.1-or-later
# This is an independent project, not a ParticleOS profile.
[Config]
MinimumVersion=26

[Distribution]
Distribution=arch
RepositoryKeyCheck=yes

[Output]
Format=directory
Output=rootfs
ManifestFormat=

[Build]
ToolsTree=default
ToolsTreeProfiles=
ToolsTreeProfiles=package-manager
Incremental=no
History=no

[Content]
Packages=
        base
        base-devel
        git
        python
        dhcpcd
        ca-certificates
        archlinux-keyring
Bootable=no

[Validation]
SecureBoot=no
SignExpectedPcr=no
Verity=no
