# SPDX-License-Identifier: LGPL-2.1-or-later
[options]
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Required

[core]
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch

[extra]
Server = https://fastly.mirror.pkgbuild.com/$repo/os/$arch
