general {
    output_format = "i3bar"
    colors = false
    interval = 5
    color_good = "#aaff00"
    color_degraded = "#00dddd"
    color_bad = "#ff8800"
    markup = "pango"
}

order += "cpu_temperature 0"
order += "memory"
order += "wireless _first_"
order += "battery 0"
order += "tztime localdate"
order += "tztime localtime"

cpu_temperature 0 {
        format = "<span color='#cc241d' size='large'>󱠇 </span> <span bgcolor='#cc241d' foreground='#3c3836'> %degrees °C </span>"
        max_threshold = 50
}

memory {
        format = "<span color='#98971a' size='large'> </span> <span bgcolor='#98971a' foreground='#3c3836'> %used </span>"
        threshold_degraded = "10%"
        format_degraded = "MEMORY: %free"
}

wireless _first_ {
        format_up = "<span color='#d79921' size='large'> </span> <span bgcolor='#d79921' foreground='#3c3836'>%quality %essid </span>"
        format_down = "<span color='#d79921'>  Offline</span>"
}

battery 0 {
        format = "<span color='#458588' size='large'>%status</span> <span bgcolor='#458588' foreground='#3c3836'> %percentage </span>"
        format_down = "No battery"
        status_chr = "⚡ "
        status_bat = " "
        status_unk = "? UNK"
        status_full = "󰂄 FULL"
        path = "/sys/class/power_supply/BAT%d/uevent"
        low_threshold = 10
        last_full_capacity = true
}

tztime localdate {
        format = "<span color='#b16286' size='large'> </span> <span bgcolor='#b16286' foreground='#3c3836'> %a %d-%m-%Y </span>"
}

tztime localtime {
        format = "<span color='#689d6a' size='large'> </span><span bgcolor='#689d6a' foreground='#3c3836'> %I:%M %p </span> "
}
